import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  appBar: {
    paddingTop: 40,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 12,
    justifyContent: 'space-between',
    borderBottomColor: '#eee',
    borderBottomWidth: 1,
    minHeight: 64,
  },
  appBarTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 100,
  },
  statusTag: {
    alignSelf: 'flex-start',
    backgroundColor: '#3A9B78',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 6,
    marginBottom: 16,
  },
  statusText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  profilePic: {
    width: 90,
    height: 90,
    borderRadius: 45,
    alignSelf: 'center',
    marginBottom: 20,
    backgroundColor: '#F0F0F0',
  },
  heading: {
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '500',
    marginBottom: 6,
  },
  drheading: {
    fontSize: 16,
    textAlign: 'center',
    color: '#707070',
    marginBottom: 6,
  },
  detailsText: {
    textAlign: 'center',
    color: '#888',
    fontSize: 14,
    marginBottom: 12,
  },
  dateTimeText: {
    textAlign: 'center',
    fontSize: 15,
    marginBottom: 10,
    color: '#707070',
  },
  dividerLine: {
    height: 1,
    backgroundColor: '#E0E0E0',
    marginVertical: 16,
    width: '100%',
  },
  linkSection: {
    marginBottom: 24,
  },
  meetingLabel: {
    fontSize: 15,
    color: '#444',
    marginBottom: 4,
    fontWeight: '500',
  },
  meetingLink: {
    fontSize: 15,
    color:'#707070'
  },
  joinButton: {
    position: 'absolute',
    bottom: 20,
    height: 48,
    alignSelf: 'center',
    flexDirection: 'row',
    backgroundColor: '#2B6EF7',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    minWidth: 360,
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  joinButtonText: {
    color: '#fff',
    fontSize: 16,
    marginRight: 8,
    fontWeight: '600',
  },
  iconRight: {
    marginTop: -2,
  },
  headerBanner: {
    backgroundColor: "#7A3DB61A",
    paddingVertical: 4,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 8,
    marginTop: 20,
    marginBottom: 20,
  },
  headerBannerText: {
    color: '#7A3DB6',
    fontSize: 14,
    fontWeight: '400',
  },
  spacer: {
    width: 24,
  },
});
